//! Microchess rules: position, move representation, make/unmake, FEN in/out,
//! perft. 4x5 board, square index `idx = rank*4 + file` with rank 0 = White's
//! back rank (a1 = 0, d1 = 3, a5 = 16, d5 = 19).
//!
//! Piece encoding follows `reference/mgen.cpp`:
//! 0 = empty; white P=1 N=2 B=3 R=4 Q=5 K=6; black = white + 8.
//!
//! Rules notes (see docs/SPEC.md):
//! * no double pawn step, therefore no en passant;
//! * promotion on the last rank to n/b/r/q is mandatory;
//! * castling is `a1c1` / `a5c5` only; rights are lost when the king moves,
//!   the rook moves, or the rook's home square is captured on.

pub mod codec;
pub mod keystream;
pub mod matclass;
pub mod movegen;
pub mod tt;

pub const BOARD_LEN: usize = 20;

// Piece codes.
pub const EMPTY: u8 = 0;
pub const WP: u8 = 1;
pub const WN: u8 = 2;
pub const WB: u8 = 3;
pub const WR: u8 = 4;
pub const WQ: u8 = 5;
pub const WK: u8 = 6;
pub const BP: u8 = 9;
pub const BN: u8 = 10;
pub const BB: u8 = 11;
pub const BR: u8 = 12;
pub const BQ: u8 = 13;
pub const BK: u8 = 14;

// Castling right bits.
pub const CASTLE_W: u8 = 1;
pub const CASTLE_B: u8 = 2;

/// The start position FEN from docs/SPEC.md. Note the non-standard castling
/// field `Dd`: the single rook per side lives on the d-file.
pub const START_FEN: &str = "kbnr/3p/4/3P/KBNR w Dd - 0 1";

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Move {
    pub from: u8,
    pub to: u8,
    /// Promotion piece as a *white* piece code (WN..=WQ), or 0 for none.
    pub promo: u8,
    /// 0 = normal, 1 = White castle a1c1, 2 = Black castle a5c5.
    pub castle: u8,
}

impl Move {
    pub fn new(from: u8, to: u8) -> Move {
        Move { from, to, promo: 0, castle: 0 }
    }

    /// UCI coordinate string, e.g. `d2d3`, `a1c1`, `c4c5q`.
    pub fn uci(self) -> String {
        let mut s = String::with_capacity(5);
        push_sq(&mut s, self.from);
        push_sq(&mut s, self.to);
        if self.promo != 0 {
            // self.promo is a white piece code in WN..=WQ => N B R Q.
            let idx = (self.promo - WN) as usize;
            s.push(['n', 'b', 'r', 'q'][idx]);
        }
        s
    }
}

fn push_sq(s: &mut String, sq: u8) {
    s.push((b'a' + (sq % 4)) as char);
    s.push((b'1' + (sq / 4)) as char);
}

impl std::fmt::Display for Move {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.uci())
    }
}

/// Information needed to undo a move.
#[derive(Clone, Copy)]
pub struct Undo {
    captured: u8,
    castling: u8,
    halfmove_clock: u16,
    fullmove_number: u16,
}

#[derive(Clone, Copy)]
pub struct Position {
    pub board: [u8; BOARD_LEN],
    pub white_to_move: bool,
    /// bit 0 (CASTLE_W): White may castle a1c1; bit 1 (CASTLE_B): Black a5c5.
    pub castling: u8,
    pub halfmove_clock: u16,
    pub fullmove_number: u16,
}

pub fn startpos() -> Position {
    Position::from_fen(START_FEN).expect("built-in start FEN must parse")
}

impl Position {
    pub fn empty() -> Position {
        Position {
            board: [EMPTY; BOARD_LEN],
            white_to_move: true,
            castling: 0,
            halfmove_clock: 0,
            fullmove_number: 1,
        }
    }

    pub fn is_white_piece(p: u8) -> bool {
        (WP..=WK).contains(&p)
    }

    pub fn is_black_piece(p: u8) -> bool {
        (BP..=BK).contains(&p)
    }

    /// Apply `m`, returning the info needed by [`Position::unmake`].
    /// Assumes `m` is pseudo-legal (generated by [`movegen`] for this position).
    pub fn make(&mut self, m: Move) -> Undo {
        let undo = Undo {
            captured: self.board[m.to as usize],
            castling: self.castling,
            halfmove_clock: self.halfmove_clock,
            fullmove_number: self.fullmove_number,
        };
        let p = self.board[m.from as usize];
        self.board[m.from as usize] = EMPTY;
        self.board[m.to as usize] = if m.promo != 0 {
            if self.white_to_move { m.promo } else { m.promo + 8 }
        } else {
            p
        };
        if m.castle == 1 {
            // King a1->c1 already handled above (from=a1,to=c1); move the rook d1->b1.
            self.board[0] = EMPTY;
            self.board[3] = EMPTY;
            self.board[2] = WK;
            self.board[1] = WR;
        } else if m.castle == 2 {
            self.board[16] = EMPTY;
            self.board[19] = EMPTY;
            self.board[18] = BK;
            self.board[17] = BR;
        }

        // Castling rights: lost when the king moves, the rook moves, or the
        // rook's home square (d1 = 3 / d5 = 19) is captured on. Ported verbatim
        // from reference/mgen.cpp (which also clears on a king leaving a1/a5 —
        // subsumed by the king-move test).
        if p == WK || m.from == 3 || m.to == 3 || m.from == 0 {
            self.castling &= !CASTLE_W;
        }
        if p == BK || m.from == 19 || m.to == 19 || m.from == 16 {
            self.castling &= !CASTLE_B;
        }

        // Clocks (not exercised by perft but part of the game state).
        if p == WP || p == BP || undo.captured != EMPTY {
            self.halfmove_clock = 0;
        } else {
            self.halfmove_clock += 1;
        }
        if !self.white_to_move {
            self.fullmove_number += 1;
        }
        self.white_to_move = !self.white_to_move;
        undo
    }

    /// Revert the most recent [`Position::make`] with its returned `Undo`.
    pub fn unmake(&mut self, m: Move, undo: Undo) {
        self.white_to_move = !self.white_to_move;
        self.fullmove_number = undo.fullmove_number;
        self.halfmove_clock = undo.halfmove_clock;
        self.castling = undo.castling;

        let mover = if m.promo != 0 {
            if self.white_to_move { WP } else { BP }
        } else {
            self.board[m.to as usize]
        };
        self.board[m.from as usize] = mover;
        self.board[m.to as usize] = undo.captured;

        if m.castle == 1 {
            self.board[2] = EMPTY;
            self.board[1] = EMPTY;
            self.board[0] = WK;
            self.board[3] = WR;
        } else if m.castle == 2 {
            self.board[18] = EMPTY;
            self.board[17] = EMPTY;
            self.board[16] = BK;
            self.board[19] = BR;
        }
    }

    /// Parse a FEN. The castling field accepts `D`/`d` (this game's notation)
    /// and `K`/`k`. The en-passant field must be `-` (the game has no e.p.);
    /// halfmove and fullmove fields default to `0 1` when absent.
    pub fn from_fen(fen: &str) -> Result<Position, String> {
        let parts: Vec<&str> = fen.split_whitespace().collect();
        if parts.len() < 2 {
            return Err(format!("FEN needs at least placement and side fields: {fen:?}"));
        }
        let mut pos = Position::empty();

        let ranks: Vec<&str> = parts[0].split('/').collect();
        if ranks.len() != 5 {
            return Err(format!("FEN placement must have 5 ranks: {fen:?}"));
        }
        for (i, row) in ranks.iter().enumerate() {
            let rank = 4 - i; // first FEN rank is rank 5
            let mut file: i32 = 0;
            for c in row.chars() {
                if let Some(d) = c.to_digit(10) {
                    file += d as i32;
                } else {
                    if !(0..4).contains(&file) {
                        return Err(format!("rank {row:?} overflows the board"));
                    }
                    pos.board[(rank * 4 + file as usize) as usize] = match c {
                        'P' => WP, 'N' => WN, 'B' => WB, 'R' => WR, 'Q' => WQ, 'K' => WK,
                        'p' => BP, 'n' => BN, 'b' => BB, 'r' => BR, 'q' => BQ, 'k' => BK,
                        other => return Err(format!("unknown piece char {other:?}")),
                    };
                    file += 1;
                }
            }
            if file != 4 {
                return Err(format!("rank {row:?} does not cover exactly 4 files"));
            }
        }

        match parts[1] {
            "w" => pos.white_to_move = true,
            "b" => pos.white_to_move = false,
            other => return Err(format!("bad side-to-move field {other:?}")),
        }

        pos.castling = 0;
        if parts.len() > 2 && parts[2] != "-" {
            for c in parts[2].chars() {
                match c {
                    'D' | 'K' => pos.castling |= CASTLE_W,
                    'd' | 'k' => pos.castling |= CASTLE_B,
                    other => return Err(format!("bad castling char {other:?}")),
                }
            }
        }

        if parts.len() > 3 && parts[3] != "-" {
            return Err(format!("microchess has no en passant; expected '-': {:?}", parts[3]));
        }

        pos.halfmove_clock = parts.get(4).and_then(|s| s.parse().ok()).unwrap_or(0);
        pos.fullmove_number = parts.get(5).and_then(|s| s.parse().ok()).unwrap_or(1);

        Ok(pos)
    }

    pub fn to_fen(&self) -> String {
        let mut fen = String::new();
        for rank in (0..5).rev() {
            let mut empty = 0;
            for file in 0..4 {
                let p = self.board[rank * 4 + file];
                if p == EMPTY {
                    empty += 1;
                } else {
                    if empty > 0 {
                        fen.push_str(&empty.to_string());
                        empty = 0;
                    }
                    fen.push(piece_char(p));
                }
            }
            if empty > 0 {
                fen.push_str(&empty.to_string());
            }
            if rank > 0 {
                fen.push('/');
            }
        }
        fen.push(' ');
        fen.push(if self.white_to_move { 'w' } else { 'b' });
        fen.push(' ');
        if self.castling == 0 {
            fen.push('-');
        } else {
            if self.castling & CASTLE_W != 0 {
                fen.push('D');
            }
            if self.castling & CASTLE_B != 0 {
                fen.push('d');
            }
        }
        fen.push_str(" - ");
        fen.push_str(&self.halfmove_clock.to_string());
        fen.push(' ');
        fen.push_str(&self.fullmove_number.to_string());
        fen
    }

    /// Resolve a UCI coordinate string against this position (needed because
    /// castling moves are distinguished by their squares only).
    pub fn move_from_uci(&self, s: &str) -> Option<Move> {
        let bytes = s.as_bytes();
        if bytes.len() < 4 {
            return None;
        }
        let from = parse_sq(bytes[0], bytes[1])?;
        let to = parse_sq(bytes[2], bytes[3])?;
        let promo = if bytes.len() >= 5 {
            match bytes[4] {
                b'n' => WN, b'b' => WB, b'r' => WR, b'q' => WQ,
                _ => return None,
            }
        } else {
            0
        };
        let mut m = Move { from, to, promo, castle: 0 };
        let p = self.board[from as usize];
        if p == WK && from == 0 && to == 2 {
            m.castle = 1;
        } else if p == BK && from == 16 && to == 18 {
            m.castle = 2;
        }
        Some(m)
    }
}

fn parse_sq(file_c: u8, rank_c: u8) -> Option<u8> {
    if !(b'a'..=b'd').contains(&file_c) || !(b'1'..=b'5').contains(&rank_c) {
        return None;
    }
    Some(((rank_c - b'1') * 4) + (file_c - b'a'))
}

fn piece_char(p: u8) -> char {
    match p {
        WP => 'P', WN => 'N', WB => 'B', WR => 'R', WQ => 'Q', WK => 'K',
        BP => 'p', BN => 'n', BB => 'b', BR => 'r', BQ => 'q', BK => 'k',
        _ => '?',
    }
}

/// Count leaf nodes at `depth` below `pos`. `pos` is left unchanged.
pub fn perft(pos: &Position, depth: u32) -> u64 {
    if depth == 0 {
        return 1;
    }
    let mut pos = *pos;
    perft_inner(&mut pos, depth)
}

fn perft_inner(pos: &mut Position, depth: u32) -> u64 {
    let moves = movegen::legal_moves(pos);
    if depth == 1 {
        return moves.len() as u64;
    }
    let mut nodes = 0;
    for m in moves {
        let undo = pos.make(m);
        nodes += perft_inner(pos, depth - 1);
        pos.unmake(m, undo);
    }
    nodes
}

/// Standard divide output: `(uci, count)` per root move at `depth >= 1`,
/// sorted by UCI string so it can be diffed directly against the reference
/// generator's divide.
pub fn divide(pos: &Position, depth: u32) -> Vec<(String, u64)> {
    let mut pos = *pos;
    let mut rows: Vec<(String, u64)> = Vec::new();
    for m in movegen::legal_moves(&pos) {
        let undo = pos.make(m);
        let n = if depth <= 1 { 1 } else { perft_inner(&mut pos, depth - 1) };
        pos.unmake(m, undo);
        rows.push((m.uci(), n));
    }
    rows.sort_by(|a, b| a.0.cmp(&b.0));
    rows
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fen_round_trip_start() {
        let pos = startpos();
        assert_eq!(pos.to_fen(), START_FEN);
    }

    #[test]
    fn fen_accepts_kk_castling_aliases() {
        let pos = Position::from_fen("kbnr/3p/4/3P/KBNR w Kk - 0 1").unwrap();
        assert_eq!(pos.to_fen(), START_FEN);
    }

    #[test]
    fn board_orientation() {
        let pos = startpos();
        assert_eq!(pos.board[0], WK); // a1
        assert_eq!(pos.board[3], WR); // d1
        assert_eq!(pos.board[7], WP); // d2
        assert_eq!(pos.board[15], BP); // d4
        assert_eq!(pos.board[16], BK); // a5
        assert_eq!(pos.board[19], BR); // d5
        assert_eq!(pos.board[12], EMPTY); // a4
    }

    #[test]
    fn move_uci_strings() {
        let pos = startpos();
        assert_eq!(pos.move_from_uci("d2d3").map(|m| m.uci()), Some("d2d3".into()));
        assert_eq!(pos.move_from_uci("a1c1").map(|m| m.castle), Some(1));
    }

    #[test]
    fn make_unmake_restores_position() {
        // Walk every legal line to depth 3 and verify unmake restores the FEN.
        let original = startpos();
        let fen = original.to_fen();
        let mut pos = original;
        walk_and_check(&mut pos, &fen, 3);
    }

    fn walk_and_check(pos: &mut Position, _root_fen: &str, depth: u32) {
        let baseline = pos.to_fen();
        for m in movegen::legal_moves(pos) {
            let undo = pos.make(m);
            if depth > 1 {
                walk_and_check(pos, &baseline, depth - 1);
            }
            pos.unmake(m, undo);
            assert_eq!(pos.to_fen(), baseline, "unmake failed after {}", m.uci());
        }
    }
}
